clustering:
  kmeans:
    n_clusters: 5
    random_state: 42
  hdbscan:
    min_cluster_size: 20

dimensionality_reduction:
  pca:
    n_components: 2
  umap:
    n_components: 2
    random_state: 42

preprocessing:
  scaler: robust #robust or minmax or standard